server:
  port: 8001
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ueae?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: 123

#    本地连正式库
#    url: jdbc:mysql://117.144.188.8:6033/ueae?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
#    username: root
#    password: igQ$3f0AAm

#    服务器正式库
    url: jdbc:mysql://10.240.32.9:3306/ueae?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: igQ$3f0AAm

#  mail:
#      host: smtp.sina.com
#      username: wondersjmail@sina.com
#      password: 123abc
#      nick: Shawn
#      properties:
#        mail:
#          debug: true
#          smtp:
#            auth: true
#            starttls:
#              enable: true
#              required: true
  jpa:
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false